### ISSUE TITLE
Please support `statusBar.background` and `activityBar.background`

### ISSUE THREAD

**Issue by martin-braun** [kensleDev/vscode-nvim-ui#10]
On MacOS, there is not square that is changing color on the bottom left corner. It would be nice if it was possible to change the entire status bar and/or activity bar background using this extension.

**Comment by martin-braun** [comment]
`statusBar.background` works, although not documented, so maybe testing this for all platforms and then document it?

**Comment by kensleDev** [comment]
Hi @martin-braun ,

I apologize for the delay in responding – I've been a bit out of the loop with the repository, but I'm now refocusing my efforts on it. Regarding your query, the current code does not target specific settings, which means you can freely utilize any valid VS Code UI settings. I appreciate your suggestions and plan to update the README to make this clearer and incorporate your suggestions.

Thank you for your patience and contribution!

**Comment by kensleDev** [comment]
Merged into master, plugin pending release (0.1.4)
