### ISSUE TITLE
Do not overwrite `workbench.colorCustomizations` entirely

### ISSUE THREAD

**Issue by martin-braun** [kensleDev/vscode-nvim-ui#11]
If there is already a `workbench.colorCustomizations` in the user's `settings.json` you should not replace the entire object. I try to set `statusBar.foreground` to `#000000`, but whenever I enter or leave insert mode, it will be removed, because this extension replaces the entire object of it instead of merging properly.

This is undesirable.

**Comment by kensleDev** [comment]
Thanks for you contribution. Sorry I've not been keeping up with this. Merged in with #12, new plugin release pending (0.1.4)

**Comment by martin-braun** [comment]
@kensleDev Thanks for taking action, it wasn't a big deal (I got used to it), but I certainly appreciate that you finally got time to look into this. :)
