### ISSUE TITLE
Settings for custom cursor colors are not working

### ISSUE THREAD

**Issue by qdddddd** [kensleDev/vscode-nvim-ui#5]
These settings writing in the doc are not working:

```json
"workbench.nvimColorNormal": "#ffc600",
"workbench.nvimColorInsert": "#D32F2F",
"workbench.nvimColorVisual": "#673AB7",
"workbench.nvimColorReplace": "#000"
```

Checked your source code. Were they changed to the following?

```json
"nvim-ui.nvimColorNormal": "#ffc600",
"nvim-ui.nvimColorInsert": "#D32F2F",
"nvim-ui.nvimColorVisual": "#673AB7",
"nvim-ui.nvimColorReplace": "#000"
```

**Comment by tieniu1** [comment]
Yes, I found it too.` "workbench.nvimColorCustomizationKeys"` --> `"nvim-ui.nvimColorCustomizationKeys"`

**Comment by kensleDev** [comment]
Apologies, these were changed when merging the last PR. I will get the docs updated ASAP.

**Comment by kensleDev** [comment]
Updated README [https://github.com/kensleDev/vscode-nvim-ui/commit/190644acd7232e7d1b634f1643645af9ac7ecd1b](url)
